### PR TITLE
NOISSUE-Add service filter

### PR DESCRIPTION
**Pull request by 1998-felix**
### What does this do?
Add service filter to callhome sdk

### Which issue(s) does this PR fix/relate to?
Resolves ultravioletrs/issues#271

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

### CODE REVIEW

**Comment by drasko** [comment]
@SammyOina this one also, please

**Comment by ianmuchyri** [comment]
@1998-felix  Some of the commits in this PR have already been merged: `Add city filter `and `Fix missing country in OpenAPI`. Also, `Add version filter` is a commit in another PR #21

**Comment by SammyOina** [comment]
To be merged after #21

**Review by SammyOina — APPROVED** [review]
LGTM, should be ok to merge after rebase and should be merged after #21

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
